[workspace]
members = [
  "common",
  # "terminal",
  # "desktop",
  # "web",
  "poc-linear",
  # "poc-fractal",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
