[package]
name = "fractory-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.21.3"
# macroquad = "0.3.23"
indexmap = "*"
num_enum = "0.5.7"

